DROP TABLE ODPOWIEDZI;
DROP TABLE PYTANIA;
DROP TABLE ANKIETY;
DROP TABLE KLIENCI;
DROP TABLE SPRZEDAWCY;
DROP TABLE DEALERZY;

DROP SEQUENCE PYT_SEQ;
DROP SEQUENCE ANK_SEQ;
DROP SEQUENCE SPRZED_SEQ;
DROP SEQUENCE DEAL_SEQ;

--DROP TRIGGER PYT_SEQ_TRIG;
--DROP TRIGGER ANK_SEQ_TRIG;
--DROP TRIGGER KLI_SEQ_TRIG;
--DROP TRIGGER SPRZED_SEQ_TRIG;
--DROP TRIGGER DEAL_SEQ_TRIG;